### ISSUE TITLE
test_resource_schema_foreign_key_Field_field randomly fails for Python 3

### ISSUE THREAD

**Issue by trickvi** [trickvi/datapackage#55]
The test ``test_resource_schema_foreign_key_Field_field`` when run in Travis. Making the build pass is just a matter of rerunning the tests for the failing Python (This only happens for Python 3). This is the output:

    ERROR: test_resource.TestDatapackage.test_resource_schema_foreign_key_Field_field
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/home/travis/build/trickvi/datapackage/tests/test_resource.py", line 609, in test_resource_schema_foreign_key_Field_field
        fields=villain, reference=villains)
      File "/home/travis/build/trickvi/datapackage/datapackage/util.py", line 42, in __init__
        self.__setattr__(key, value)
      File "/home/travis/build/trickvi/datapackage/datapackage/schema.py", line 137, in __setattr__
        'Fields must have the same type as Reference fields')
    TypeError: Fields must have the same type as Reference fields
    ----------------------------------------------------------------------
    Ran 137 tests in 0.323s
    FAILED (errors=1)
    The command "nosetests" exited with 1.
    Done. Your build exited with 1.

**Comment by pwalsh** [comment]
@trickvi can we close this one?

**Comment by trickvi** [comment]
Since the repo will be maintained by the frictionlessdata and was developed from scratch (hence not being an issue) I'm closing this issue.
